name: Build Windows EXE

on:
  push:
    branches: [ "v.3.3.0" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # 3.14는 너무 최신이라 라이브러리 호환성 문제가 생길 수 있어 3.12 권장

    - name: Install Poetry & PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install poetry pyinstaller  # 여기서 pyinstaller를 직접 설치

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi

    - name: Build EXE with PyInstaller
      run: |
        # poetry run 대신 직접 pyinstaller 실행
        pyinstaller --onefile --noconsole --hidden-import=pynput.keyboard --hidden-import=pynput.mouse --clean run_auttic.py

    - name: Check Build Output
      run: |
        ls dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable
        path: dist/*.exe
